Repository PayKids/paykids-android, pull requests merged in 2025-01, with the labels that each got.

#32 [PAY-016] 학습하기 페이지 api, 용돈일기 다이얼로그 수정
  PayKids/app/src/main/AndroidManifest.xml
  PayKids/data/src/main/java/com/paykids/data/datasource/ChatRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/ChatRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/di/ChatUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/DatasourceModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/NetworkModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/RepositoryModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/ServiceModule.kt
  PayKids/data/src/main/java/com/paykids/data/model/ChatResponseDTO.kt
  PayKids/data/src/main/java/com/paykids/data/repository/ChatRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/ChatService.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/DetailConsume.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/DetailTransaction.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/ChatRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/chat/SendChatUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/Screens.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisCategoryConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DetailConsumeAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryMonthFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeActivity.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/ModifyInfoFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/PolicyFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/StudyFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/StudyRvAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/StudyViewModel.kt
  PayKids/presentation/src/main/res/drawable/ic_left_white.xml
  PayKids/presentation/src/main/res/layout/dialog_diary.xml
  PayKids/presentation/src/main/res/layout/fragment_analysis_consume.xml
  PayKids/presentation/src/main/res/layout/fragment_modify_info.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_entry.xml
  PayKids/presentation/src/main/res/layout/item_chat_other.xml
  PayKids/presentation/src/main/res/layout/item_diary_day.xml
Labels: ✨ Feature, 🔨 Refactor

#34 [PAY-017] 유저 회원가입 api 연동
  PayKids/data/src/main/java/com/paykids/data/datasource/AuthRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasource/UserRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/AuthRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/UserRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/di/AuthUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/DatasourceModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/KakaoAuthUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/RepositoryModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/ServiceModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/UserUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/mapper/SignMapper.kt
  PayKids/data/src/main/java/com/paykids/data/mapper/UserMapper.kt
  PayKids/data/src/main/java/com/paykids/data/model/BaseResponse.kt
  PayKids/data/src/main/java/com/paykids/data/model/UserInfoResponseDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/UserTokenResponseDTO.kt
  PayKids/data/src/main/java/com/paykids/data/repository/AuthRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/KakaoAuthRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/UserRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/AuthService.kt
  PayKids/data/src/main/java/com/paykids/data/service/KakaoAuthService.kt
  PayKids/data/src/main/java/com/paykids/data/service/UserService.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/auth/SignInInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/auth/UserSignInInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/user/UserInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/AuthRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/KakaoAuthRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/UserRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/auth/KakaoAuthUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/auth/SaveSignInInfoUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/auth/SignInUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/auth/SignOutUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/auth/WithdrawalUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/user/GetUserInfoUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/user/SaveNicknameUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DetailConsumeAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/MyPageFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/MyPageViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignInProviderFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignNicknameFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignViewModel.kt
Labels: ✨ Feature

#37 [PAY-019] 퀴즈 페이지 UI
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/ExitDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizImageFragment.kt
  PayKids/presentation/src/main/res/drawable/ic_cancel_white.xml
  PayKids/presentation/src/main/res/drawable/ic_check_white.xml
  PayKids/presentation/src/main/res/drawable/ic_left_black.xml
  PayKids/presentation/src/main/res/drawable/img_king_sejong.png
  PayKids/presentation/src/main/res/drawable/img_quiz_clear_box.png
  PayKids/presentation/src/main/res/drawable/img_quiz_image_box.png
  PayKids/presentation/src/main/res/drawable/img_quiz_image_box_blue.png
  PayKids/presentation/src/main/res/drawable/img_quiz_image_box_red.png
  PayKids/presentation/src/main/res/drawable/img_quiz_input_box.png
  PayKids/presentation/src/main/res/drawable/img_quiz_item_default.png
  PayKids/presentation/src/main/res/drawable/img_quiz_text_box.png
  PayKids/presentation/src/main/res/drawable/img_quiz_text_box_blue.png
  PayKids/presentation/src/main/res/drawable/img_quiz_text_box_red.png
  PayKids/presentation/src/main/res/drawable/shape_bg_quiz_image.xml
  PayKids/presentation/src/main/res/drawable/shape_bg_quiz_image2.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_answer_input_box.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_box_blue.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_box_default.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_box_red.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_clear_box.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_correct_answer_box.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_decision_box.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_decision_box_gray.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_exit_box.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_wrong_answer_box.xml
  PayKids/presentation/src/main/res/drawable/shape_quiz_wrong_answer_note_box.xml
  PayKids/presentation/src/main/res/layout/dialog_quiz_exit.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_clear.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_image.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_multiple_choice.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_multiple_choice_img.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_short_answer.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_short_answer_img.xml
  PayKids/presentation/src/main/res/layout/item_answer_box.xml
  PayKids/presentation/src/main/res/navigation/nav_graph.xml
  PayKids/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#38 [PAY-020] 일기 페이지 API
  PayKids/data/src/main/java/com/paykids/data/datasource/ExpenseRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasource/IncomeRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/ExpenseRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/IncomeRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/di/DatasourceModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/ExpenseUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/IncomeUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/RepositoryModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/ServiceModule.kt
  PayKids/data/src/main/java/com/paykids/data/mapper/AllowanceMapper.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/AddExpenseRequestDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/DayDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/DayDTOItem.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthAllCategoryDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthAllCategoryDTOItem.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthCategoryDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthCategoryDTOItem.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthDailyDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthDailyDTOItem.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthMostCategoryDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/UpdateExpenseRequestDTO.kt
  PayKids/data/src/main/java/com/paykids/data/repository/ExpenseRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/IncomeRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/AuthService.kt
  PayKids/data/src/main/java/com/paykids/data/service/ExpenseService.kt
  PayKids/data/src/main/java/com/paykids/data/service/IncomeService.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/CategoryInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/DayInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/allowance/DayInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/allowance/MonthAllCategoryInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/allowance/MonthCategoryInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/allowance/MonthDailyInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/allowance/MonthMostCategory.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/ExpenseRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/IncomeRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/AddExpenseUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/GetDayExpenseUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/GetMonthAllCategoryExpenseUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/GetMonthCategoryExpenseUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/GetMonthDailyExpenseUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/GetMonthMostCategoryUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/GetMonthTotalExpenseUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/UpdateExpenseUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/income/AddIncomeUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/income/GetDayIncomeUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/income/GetMonthAllCategoryIncomeUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/income/GetMonthCategoryIncomeUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/income/GetMonthDailyIncomeUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/income/GetMonthTotalIncomeUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/income/UpdateIncomeUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisCategoryConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryDayCalendarAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryMonthFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/ModifyInfoFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/MyPageViewModel.kt
Labels: ✨ Feature

#40 [PAY-021] 카테고리 추가, 삭제 api
  PayKids/app/src/main/AndroidManifest.xml
  PayKids/data/src/main/java/com/paykids/data/datasource/ChatRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasource/ExpenseCategoryRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasource/IncomeCategoryRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/ChatRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/ExpenseCategoryRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/IncomeCategoryRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/di/DatasourceModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/ExpenseCategoryUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/IncomeCategoryUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/RepositoryModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/ServiceModule.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowanceCategory/CategoryListDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowanceCategory/CategoryListDTOItem.kt
  PayKids/data/src/main/java/com/paykids/data/repository/ChatRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/ExpenseCategoryRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/IncomeCategoryRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/ChatService.kt
  PayKids/data/src/main/java/com/paykids/data/service/ExpenseCategoryService.kt
  PayKids/data/src/main/java/com/paykids/data/service/IncomeCategoryService.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/ChatItem.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/allowanceCategory/CategoryInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/ChatRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/ExpenseCategoryRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/IncomeCategoryRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/chat/SendChatUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expenseCategory/DeleteExpenseCategoryUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expenseCategory/SaveExpenseCategoryUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/incomeCategory/DeleteIncomeCategoryUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/incomeCategory/SaveIncomeCategoryUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/StudyFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/StudyRvAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/StudyViewModel.kt
  PayKids/presentation/src/main/res/layout/item_chat_my.xml
  PayKids/presentation/src/main/res/layout/item_chat_other.xml
Labels: ✨ Feature

#41 [PAY-022] 홈 페이지 API 적용
  PayKids/data/src/main/java/com/paykids/data/datasource/QuizRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/QuizRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/di/DatasourceModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/QuizUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/RepositoryModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/ServiceModule.kt
  PayKids/data/src/main/java/com/paykids/data/mapper/QuizMapper.kt
  PayKids/data/src/main/java/com/paykids/data/model/QuizResponseDTO.kt
  PayKids/data/src/main/java/com/paykids/data/repository/QuizRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/QuizService.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/quiz/Quiz.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/QuizRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/quiz/GetQuizUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/quiz/GetStageCountUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/quiz/GetStageNameUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/quiz/GetStageToGoUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryFragment.kt
  PayKids/presentation/src/main/res/layout/fragment_home.xml
  PayKids/presentation/src/main/res/navigation/nav_graph.xml
Labels: ✨ Feature

#42 [PAY-023] 소비/수입 내역 카테고리 통계 페이지
  PayKids/build.gradle.kts
  PayKids/data/src/main/java/com/paykids/data/di/DatasourceModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/RepositoryModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/ServiceModule.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthMostCategoryDTO.kt
  PayKids/data/src/main/java/com/paykids/data/model/allowance/MonthMostCategoryDTOItem.kt
  PayKids/data/src/main/java/com/paykids/data/repository/ExpenseRepositoryImpl.kt
  PayKids/presentation/build.gradle.kts
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisCategoryConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/ConsumeCategoryAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DetailConsumeAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryDayCalendarAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryMonthCalendarStateAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryMonthFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignInProviderFragment.kt
  PayKids/presentation/src/main/res/navigation/nav_graph.xml
  PayKids/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#44 [PAY-024] 용돈일기 다이얼로그 작업
  PayKids/app/src/main/AndroidManifest.xml
  PayKids/data/src/main/java/com/paykids/data/datasource/ExpenseCategoryRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasource/IncomeCategoryRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/ExpenseCategoryRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/IncomeCategoryRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/di/ExpenseCategoryUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/di/IncomeCategoryUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/mapper/AllowanceMapper.kt
  PayKids/data/src/main/java/com/paykids/data/mapper/CategoryMapper.kt
  PayKids/data/src/main/java/com/paykids/data/repository/DataStoreRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/ExpenseCategoryRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/ExpenseRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/IncomeCategoryRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/ExpenseCategoryService.kt
  PayKids/data/src/main/java/com/paykids/data/service/IncomeCategoryService.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/allowance/DayInfo.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/ExpenseCategoryRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/ExpenseRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/IncomeCategoryRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/datastore/ClearUserDataUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expense/GetMonthMostCategoryUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expenseCategory/AddExpenseCategoryUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/expenseCategory/GetExpenseCategoryUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/incomeCategory/AddIncomeCategoryUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/incomeCategory/GetIncomeCategoryUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/custom/CategoryProgressView.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AllowanceCategoryAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisCategoryConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/CategoryDetailAllowanceAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/CategoryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DetailConsumeAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/ModifyInfoFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/MyPageViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/PolicyFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/StudyFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignInProviderFragment.kt
  PayKids/presentation/src/main/res/layout/dialog_diary.xml
  PayKids/presentation/src/main/res/layout/fragment_analysis_allowance.xml
  PayKids/presentation/src/main/res/layout/fragment_analysis_category_allowance.xml
  PayKids/presentation/src/main/res/layout/fragment_diary.xml
  PayKids/presentation/src/main/res/layout/fragment_modify_info.xml
  PayKids/presentation/src/main/res/layout/item_analysis_allowance.xml
  PayKids/presentation/src/main/res/layout/item_category_allowance.xml
  PayKids/presentation/src/main/res/layout/item_detail_allowance.xml
  PayKids/presentation/src/main/res/navigation/nav_graph.xml
  PayKids/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#45 [PAY-025] 퀴즈 페이지 API 적용
  PayKids/data/src/main/java/com/paykids/data/datasource/QuizRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/QuizRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/mapper/QuizMapper.kt
  PayKids/data/src/main/java/com/paykids/data/model/QuizClearResponseDTO.kt
  PayKids/data/src/main/java/com/paykids/data/repository/QuizRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/QuizService.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/quiz/Quiz.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/quiz/QuizClear.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/QuizRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/quiz/CheckAnswerUseCase.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/quiz/CheckClearUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/ExitDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizClearFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizImageFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceImgFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceRvAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizShortAnswerFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizShortAnswerImgFragment.kt
  PayKids/presentation/src/main/res/drawable/shape_quiz_failed_box.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_clear.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_image.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_multiple_choice.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_multiple_choice_img.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_short_answer.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_short_answer_img.xml
  PayKids/presentation/src/main/res/layout/item_answer_box.xml
  PayKids/presentation/src/main/res/layout/item_answer_box_text.xml
  PayKids/presentation/src/main/res/navigation/nav_graph.xml
  PayKids/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#48 [PAY-026] 최종 디자인 시스템 점검, 1차 임시 배포
  PayKids/data/src/main/java/com/paykids/data/repository/KakaoAuthRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/KakaoAuthService.kt
  PayKids/domain/src/main/java/com/paykids/domain/model/DetailTransaction.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/KakaoAuthRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/auth/KakaoAuthUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/base/BaseFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisCategoryConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/AnalysisConsumeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/ModifyInfoFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/PolicyFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizClearFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizImageFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceImgFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceRvAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizShortAnswerFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizShortAnswerImgFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/StudyFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignInProviderFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignViewModel.kt
  PayKids/presentation/src/main/res/drawable/shape_quiz_decision_box.xml
  PayKids/presentation/src/main/res/layout/dialog_diary.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_entry.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_image.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_multiple_choice.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_multiple_choice_img.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_short_answer.xml
  PayKids/presentation/src/main/res/layout/fragment_sign_provider.xml
  PayKids/presentation/src/main/res/layout/fragment_study.xml
  PayKids/presentation/src/main/res/layout/item_answer_box.xml
  PayKids/presentation/src/main/res/navigation/nav_graph.xml
  PayKids/presentation/src/main/res/values/font_style.xml
  PayKids/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature, 🔨 Refactor, 🌏 Deploy, 🎨 UI Design

#49 [PAY-027] 앱 아이콘 등록
  PayKids/app/src/main/AndroidManifest.xml
  PayKids/data/src/main/java/com/paykids/data/service/KakaoAuthService.kt
  PayKids/presentation/src/main/ic_paykids-playstore.png
  PayKids/presentation/src/main/res/drawable/ic_paykids_background.xml
  PayKids/presentation/src/main/res/mipmap-anydpi-v26/ic_paykids.xml
  PayKids/presentation/src/main/res/mipmap-anydpi-v26/ic_paykids_round.xml
  PayKids/presentation/src/main/res/mipmap-hdpi/ic_paykids.webp
  PayKids/presentation/src/main/res/mipmap-hdpi/ic_paykids_foreground.webp
  PayKids/presentation/src/main/res/mipmap-hdpi/ic_paykids_round.webp
  PayKids/presentation/src/main/res/mipmap-mdpi/ic_paykids.webp
  PayKids/presentation/src/main/res/mipmap-mdpi/ic_paykids_foreground.webp
  PayKids/presentation/src/main/res/mipmap-mdpi/ic_paykids_round.webp
  PayKids/presentation/src/main/res/mipmap-xhdpi/ic_paykids.webp
  PayKids/presentation/src/main/res/mipmap-xhdpi/ic_paykids_foreground.webp
  PayKids/presentation/src/main/res/mipmap-xhdpi/ic_paykids_round.webp
  PayKids/presentation/src/main/res/mipmap-xxhdpi/ic_paykids.webp
  PayKids/presentation/src/main/res/mipmap-xxhdpi/ic_paykids_foreground.webp
  PayKids/presentation/src/main/res/mipmap-xxhdpi/ic_paykids_round.webp
  PayKids/presentation/src/main/res/mipmap-xxxhdpi/ic_paykids.webp
  PayKids/presentation/src/main/res/mipmap-xxxhdpi/ic_paykids_foreground.webp
  PayKids/presentation/src/main/res/mipmap-xxxhdpi/ic_paykids_round.webp
Labels: ✨ Feature

#50 [PAY-028] 퀴즈 이미지 로드 시 선택지 텍스트 추가
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizImageFragment.kt
Labels: ✨ Feature

#51 [PAY-029] 다이얼로그 폰 크기에 반응, 회원 탈퇴 기능 추가
  PayKids/app/src/main/AndroidManifest.xml
  PayKids/data/src/main/java/com/paykids/data/datasource/UserRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/UserRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/di/UserUseCaseModule.kt
  PayKids/data/src/main/java/com/paykids/data/repository/UserRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/KakaoAuthService.kt
  PayKids/data/src/main/java/com/paykids/data/service/UserService.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/UserRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/user/DeleteUserUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/ModifyInfoFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/MyPageViewModel.kt
  PayKids/presentation/src/main/res/layout/dialog_diary.xml
  PayKids/presentation/src/main/res/layout/fragment_modify_info.xml
Labels: ✨ Feature, 🎨 UI Design

#52 [PAY-030] 배경 이미지 scaleType 조정
  PayKids/presentation/src/main/res/layout/fragment_quiz_entry.xml
  PayKids/presentation/src/main/res/layout/fragment_sign_provider.xml
Labels: 🎨 UI Design

#53 [PAY-031] 바텀 내비게이션 디자인 변경
  PayKids/presentation/src/main/res/drawable/shape_bottom_nav.xml
  PayKids/presentation/src/main/res/layout/activity_home.xml
  PayKids/presentation/src/main/res/layout/fragment_diary.xml
  PayKids/presentation/src/main/res/values/styles.xml
Labels: 🎨 UI Design

#54 [PAY-032] 1차 QA
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/ModifyInfoFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignNicknameFragment.kt
  PayKids/presentation/src/main/res/drawable/ic_right.xml
  PayKids/presentation/src/main/res/layout/fragment_modify_info.xml
  PayKids/presentation/src/main/res/layout/fragment_mypage.xml
  PayKids/presentation/src/main/res/layout/fragment_policy.xml
  PayKids/presentation/src/main/res/layout/fragment_sign_nickname.xml
  PayKids/presentation/src/main/res/layout/item_category_allowance.xml
  PayKids/presentation/src/main/res/layout/item_detail_allowance.xml
  PayKids/presentation/src/main/res/values/strings.xml
Labels: 🐞 BugFix, 🔨 Refactor

#55 [PAY-034] 퀘스트 페이지 view
  PayKids/domain/src/main/java/com/paykids/domain/model/quest/QuestItem.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/home/HomeFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/AchievementFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/QuestAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/QuestFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/QuestListFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/QuestPagerAdapter.kt
  PayKids/presentation/src/main/res/drawable/ic_quest.png
  PayKids/presentation/src/main/res/drawable/layer_list_quest_progressbar.xml
  PayKids/presentation/src/main/res/drawable/shape_quest.xml
  PayKids/presentation/src/main/res/layout/fragment_achievement.xml
  PayKids/presentation/src/main/res/layout/fragment_quest.xml
  PayKids/presentation/src/main/res/layout/fragment_quest_list.xml
  PayKids/presentation/src/main/res/layout/item_quest.xml
  PayKids/presentation/src/main/res/menu/bottom_navigation_items.xml
  PayKids/presentation/src/main/res/navigation/nav_graph.xml
  PayKids/presentation/src/main/res/values/font_style.xml
  PayKids/presentation/src/main/res/values/strings.xml
  PayKids/presentation/src/main/res/values/styles.xml
Labels: ✨ Feature

#58 [PAY-035] 업적 페이지 view
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/AchievementFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/AchievementsAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/GridSpacingItemDecoration.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/MockAchievement.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/QuestAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quest/QuestListFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/signIn/SignNicknameFragment.kt
  PayKids/presentation/src/main/res/drawable/ic_achieve1.png
  PayKids/presentation/src/main/res/drawable/shape_quiz_box_default.xml
  PayKids/presentation/src/main/res/layout/fragment_achievement.xml
  PayKids/presentation/src/main/res/layout/item_achievement.xml
  PayKids/presentation/src/main/res/values/dimens.xml
  PayKids/presentation/src/main/res/values/font_style.xml
  PayKids/presentation/src/main/res/values/strings.xml
Labels: ✨ Feature

#60 [PAY-036] 오답 노트 풀기 구현
  PayKids/data/src/main/java/com/paykids/data/datasource/QuizRemoteDatasource.kt
  PayKids/data/src/main/java/com/paykids/data/datasourceImpl/QuizRemoteDatasourceImpl.kt
  PayKids/data/src/main/java/com/paykids/data/repository/QuizRepositoryImpl.kt
  PayKids/data/src/main/java/com/paykids/data/service/QuizService.kt
  PayKids/domain/src/main/java/com/paykids/domain/repository/QuizRepository.kt
  PayKids/domain/src/main/java/com/paykids/domain/usecase/quiz/GetIncorrectQuizNumbersUseCase.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/custom/ConfirmDialogInterface.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/CategoryDetailAllowanceAdapter.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/diary/DiaryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/ModifyInfoFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/mypage/MyPageFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/IncorrectDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizClearFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryViewModel.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizImageFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceImgFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizShortAnswerFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizShortAnswerImgFragment.kt
  PayKids/presentation/src/main/res/layout/fragment_quiz_clear.xml
  PayKids/presentation/src/main/res/layout/fragment_quiz_image.xml
  PayKids/presentation/src/main/res/navigation/nav_graph.xml
Labels: ✨ Feature

#62 [PAY-038] BGM 및 효과음 추가
  PayKids/presentation/src/main/java/com/paykids/presentation/utils/QuizSoundManager.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/ExitDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/IncorrectDialog.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizClearFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizEntryFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizImageFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizMultipleChoiceImgFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizShortAnswerFragment.kt
  PayKids/presentation/src/main/java/com/paykids/presentation/view/quiz/QuizShortAnswerImgFragment.kt
  PayKids/presentation/src/main/res/raw/cartoon_fail_trumpet.mp3
  PayKids/presentation/src/main/res/raw/coin1.mp3
  PayKids/presentation/src/main/res/raw/error5.mp3
  PayKids/presentation/src/main/res/raw/game_level_complete.mp3
  PayKids/presentation/src/main/res/raw/quiz_bgm.mp3
Labels: ✨ Feature
